name: flutter_bug_opengl_native
description: A new Flutter plugin to show a bug with opengl native
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.test.flutter_bug_opengl_native
        pluginClass: FlutterBugOpenglNativePlugin
      ios:
        pluginClass: FlutterBugOpenglNativePlugin
